services:
  - type: web
    name: nikepig-lottery-backend
    env: deno
    buildCommand: cd backend/deno-backend && deno cache mod.ts
    startCommand: cd backend/deno-backend && deno run --allow-net --allow-env mod.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BLOCKFROST_API_KEY
        value: previewyEaLt5aKLcelODYvUD4Ka8cmT41DurY0
      - key: BLOCKFROST_URL
        value: https://cardano-preview.blockfrost.io/api/v0
      - key: POOL_WALLET_ADDRESS
        sync: false
      - key: ADMIN_WALLET_ADDRESS
        sync: false 